### ISSUE TITLE
What is needed?

### ISSUE THREAD

**Issue by super9xman** [chemerisuk/cordova-plugin-firebase-inappmessaging#1]
What is needed to get this plugin to work inside Ionic apps?  This will be a fanatic plguin to add. How can I help?

**Comment by kaoecoito** [comment]
I read in the google documentation and you do not need anything other than adding the dependency libraries for it to work.
So you just need to add this plugin to your project:
cordova plugin add cordova-plugin-firebase-inappmessaging
After this run your application, all dynamic messages are generated within the Firebase Console panel, no additional code is needed in the App.

https://firebase.google.com/products/in-app-messaging/

**Comment by chemerisuk** [comment]
@super9xman read https://github.com/chemerisuk/cordova-plugin-idfa/issues/1#issuecomment-429095894
