### ISSUE TITLE
App freezing on launch

### ISSUE THREAD

**Issue by sagrawal31** [chemerisuk/cordova-plugin-firebase-inappmessaging#10]
## Description

Continuing discussion from https://github.com/chemerisuk/cordova-plugin-firebase-crash/issues/20.

After 1 full day of my research on one of our production app, I finally managed to figure out the root cause of the app being frozen because of this plugin. And this time, I can reproduce this issue in a fresh Cordova app with only this plugin installed.

Basically, as soon as the app is launching, the app is freezing and after a few minutes, the app is crashed (shows Android OS dialogue that this app is not responding).

I tried to downgrade the firebase-inapp-messaging version to `19.0.3` but it also has same issue. I tried this on different Android phone but the issue is the same.

## Environment

- Android: 9
- cordova-android: 8.1.0
- cordova-cli: 9.0.0 (cordova-lib@9.0.1)
- OS: macOS Catalina

**Comment by chemerisuk** [comment]
@sagrawal31 tried the same steps for a new project - everything builds. Are you trying to build a debug or release build?

**Comment by sagrawal31** [comment]
I have tried with the both the builds. By the way, build is working fine. This happens after we install the build and launch the app.

**Comment by chemerisuk** [comment]
@sagrawal31 do you have crash logs?

**Comment by sagrawal31** [comment]
That's what the problem is. `adb logcat AndroidRuntime:E '*:S\'` is not showing any crash log. But I can provide you with some from `adb logcat '*:E'`. Will that be of any use for you?

**Comment by chemerisuk** [comment]
@sagrawal31 post all logs you have
