### ISSUE TITLE
For Android on firebase console inappmessaging campaigns not showing impression and click counts

### ISSUE THREAD

**Issue by endless-ashes** [chemerisuk/cordova-plugin-firebase-inappmessaging#11]
I faced the issue in Android only, IOS is showing the impression and click counts on firebase console FIAM campaigns.

Getting inappmessaging popup perfectly on the app, no issue here.

But always showing 0 count for both impression and click on firebase console FIAM campaigns.

Please help! Urgently needed.

Using:
"com.google.firebase:firebase-analytics:17.3.0"
"com.google.firebase:firebase-inappmessaging-display:19.0.5"
cordova-android : 8.1.0

![image](https://user-images.githubusercontent.com/34907235/79447817-a2f1b800-800a-11ea-96fc-65ae6b21448e.png)

**Comment by radamantis200** [comment]
Hello friend can you help me implement this plugin, I have an error when building for android

**Comment by edr122** [comment]
Hello did you find the solution?  @endless-ashes
