### ISSUE TITLE
Error al compilar la app ionic 5, help 

### ISSUE THREAD

**Issue by radamantis200** [chemerisuk/cordova-plugin-firebase-inappmessaging#12]
Help please install the plugin and but I am having trouble building the app on android

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> The library com.google.firebase:firebase-iid is being requested by various other libraries at [[20.0.2,20.0.2]], but resolves to 20.1.5. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
C:\Users\sanch\Documents\DevPruebas\fotosgram\platforms\android\gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> The library com.google.firebase:firebase-iid is being requested by various other libraries at [[20.0.2,20.0.2]], but resolves to 20.1.5. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by chemerisuk** [comment]
@radamantis200 better to ask ionic team.
