### ISSUE TITLE
Wrong variable name in plugin.xml

### ISSUE THREAD

**Issue by gartorware** [chemerisuk/cordova-plugin-firebase-inappmessaging#13]
Hi, thanks for your work :smiley: 

Seems like there is an error with a variable name in latest version:

In plugin.xml, android part:
```
<preference name="ANDROID_FIREBASE_INAPPMESSAGING_VERSION" default="19.1.+"/>

<framework src="com.google.firebase:firebase-inappmessaging-display:$FIREBASE_INAPPMESSAGING_VERSION" />
```

That second line should use `ANDROID_FIREBASE_INAPPMESSAGING_VERSION` since this is the variable name now.

Regards.

**Comment by chemerisuk** [comment]
Thanks, bugfix published in v3.4.1
