### ISSUE TITLE
"InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.

### ISSUE THREAD

**Issue by yinzara** [chemerisuk/cordova-plugin-firebase-inappmessaging#15]
When running `cordova build ios` either the simulator version or device version, I get the following error:
```
error: Resource "/Users/myuser/Library/Developer/Xcode/DerivedData/1ST-grxrjkrkjhmnifeyevheojlmoinj/Build/Intermediates.noindex/ArchiveIntermediates/1ST/BuildProductsPath/Debug-iphoneos/FirebaseInAppMessaging/InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.
```

Running `pod install` does not fix the issue.

I am using the latest cocoapods 1.10.1 and the latest version of this plugin (4.0.0).

**Comment by DineshKachhot** [comment]
@yinzara any update on that, getting the same issue.

**Comment by yinzara** [comment]
Updating to the latest version of all the Firebase Pods seemed to fix it.
