### ISSUE TITLE
Build Error With Ionic3 

### ISSUE THREAD

**Issue by abomadi** [chemerisuk/cordova-plugin-firebase-inappmessaging#4]
Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/me/Desktop/Projects/project-2.1/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Failed to install 'cordova-plugin-firebase-inappmessaging': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/me/Desktop/Projects/project-2.1/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Ionic Info**
Ionic:

   Ionic CLI          : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 25 other plugins)

Utility:

   cordova-res : 0.5.2 (update available: 0.6.0)
   native-run  : 0.2.5 (update available: 0.2.8)

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.10.0 (/usr/local/Cellar/node/12.10.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8

tried to pod repo update after with the same result, also it does conflicts with the analytics plugin as well

**Plugin List**
branch-cordova-sdk 3.2.0 "branch-cordova-sdk"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 5.0.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase-analytics 2.0.4 "FirebaseAnalyticsPlugin"
cordova-plugin-firebase-dynamiclinks 3.0.0 "FirebaseDynamicLinksPlugin"
cordova-plugin-firebase-inappmessaging 2.0.3 "cordova-plugin-firebase-inappmessaging"
cordova-plugin-freshchat 1.2.0 "Freshchat plugin for Phonegap"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-purchase 8.1.1 "Purchase"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.5 "SocialSharing"
cordova-plugin-youtube-video-player 2.3.0 "CordovaYoutubeVideoPlayer"
cordova-support-google-services 1.3.1 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.5.2 "OneSignal Push Notifications"

**Comment by guibarbosadev** [comment]
have you already tried to generate a build with only this plugin installed?

**Comment by abomadi** [comment]
@guilhermebpereira not really, however i manage to build it correctly by upgrading pod version 3.0.0
