### ISSUE TITLE
FIAM displays message only once

### ISSUE THREAD

**Issue by burkongla** [chemerisuk/cordova-plugin-firebase-inappmessaging#7]
In my case: Only shows in-app message on dyanmic link login

I use firebase dynamic links with email link sign in. After I sign in with the link I receive it displays the in-app message but then it doesn't display any futher messages. It does not display anything if I restart, change page or anything. Any thoughts on what this could be?

I tried to add some data that I think might be relevant. These are the messages related to FIAM as far as I can tell:

When it works:
`
I/FIAM.Headless: Setting display event listener
I/FIAM.Headless: went foreground
I/FIAM.Headless: Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
I/FIAM.Headless: Recoverable exception while reading cache: /data/user/0/*****/files/fiam_impressions_store_file: open failed: ENOENT (No such file or directory)
I/FIAM.Headless: Fetching campaigns from service.
I/FIAM.Headless: Successfully fetched 8 messages from backend
I/FIAM.Headless: Recoverable exception while reading cache: /data/user/0/*****/files/fiam_impressions_store_file: open failed: ENOENT (No such file or directory)
I/FIAM.Headless: Already impressed Some campaign ? : false
....
I/FIAM.Display: Impression timer onFinish for: 2339382511907373056
FIAM.Headless: Recoverable exception while reading cache: /data/user/0/****/files/rate_limit_store_file: open failed: ENOENT (No such file or directory)
I/FIAM.Headless: Removing display event listener
`

When it does not work:
`
I/FIAM.Headless: went foreground
I/FIAM.Headless: Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
I/FIAM.Headless: Fetching campaigns from service.
I/FIAM.Headless: Successfully fetched 7 messages from backend
I/FIAM.Headless: Already impressed jnjjn ? : false
I/FIAM.Headless: App foreground rate limited ? : true
...
I/FIAM.Headless: Removing display event listener

`

Dependencies:
`
"cordova-plugin-firebase-analytics": "^4.0.0",
"cordova-plugin-firebase-dynamiclinks": "^3.0.0",
"cordova-plugin-firebase-inappmessaging": "^3.0.0",
"cordova-plugin-firebasex": "^6.1.0",
"cordova-plugin-splashscreen": "^5.0.3",
"cordova-support-android-plugin": "^1.0.1",
"cordova-support-google-services": "https://github.com/LuisEGR/cordova-support-google-services.git"
`

Plugin configs:
`
"cordova-plugin-firebase-dynamiclinks": {
  "APP_DOMAIN": "vitallysmartapp.firebaseapp.com",
  "PAGE_LINK_DOMAIN": "vitallysmart.page.link",
  "FIREBASE_CORE_VERSION": "17.0.+",
  "FIREBASE_DYNAMIC_LINKS_VERSION": "18.0.+"
},
"cordova-support-google-services": {},
"cordova-plugin-splashscreen": {},
"cordova-plugin-firebasex": {
  "FIREBASE_ANALYTICS_COLLECTION_ENABLED": "true",
  "FIREBASE_PERFORMANCE_COLLECTION_ENABLED": "true",
  "FIREBASE_CRASHLYTICS_COLLECTION_ENABLED": "true",
  "ANDROID_ICON_ACCENT": "#FF00FFFF",
  "ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION": "17.0.0",
  "ANDROID_FIREBASE_CORE_VERSION": "17.0.0",
  "ANDROID_FIREBASE_MESSAGING_VERSION": "19.0.0",
  "ANDROID_FIREBASE_CONFIG_VERSION": "18.0.0",
  "ANDROID_FIREBASE_PERF_VERSION": "18.0.0",
  "ANDROID_FIREBASE_AUTH_VERSION": "18.0.0",
  "ANDROID_CRASHLYTICS_VERSION": "2.10.1",
  "ANDROID_CRASHLYTICS_NDK_VERSION": "2.1.0",
  "ANDROID_SHORTCUTBADGER_VERSION": "1.1.22"
},
"cordova-plugin-camera": {
  "ANDROID_SUPPORT_V4_VERSION": "27.+"
},
"cordova-plugin-firebase-inappmessaging": {
  "FIREBASE_INAPPMESSAGING_VERSION": "19.0.+"
},
`

**Comment by chemerisuk** [comment]
FIAM displays message only once.

**Comment by guibarbosadev** [comment]
I experencied some issues on Android where the Inapp message was only been detected when some lifecycle of the activity was been triggered. Don't know if it helps you.

**Comment by burkongla** [comment]
@guilhermebpereira Do you by chance remember what lifecycle event, and was it related to the events you define in firebase by chance? In that case I have already tried with all the different events available in firebase, reopen app, make it background and then foreground again which should trigger on_foreground, but nothing happens. I also get this in the android log which I think is related to FIAM detecting that it is now foreground again but still does not fetch new in-app messages?

I/FIAM.Headless: Setting display event listener
 I/FIAM.Headless: went foreground

**Comment by sn-bhawani** [comment]
FIAM.Headless: Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
