### ISSUE TITLE
Is cordova-plugin-firebase-analytics needed?

### ISSUE THREAD

**Issue by guibarbosadev** [chemerisuk/cordova-plugin-firebase-inappmessaging#8]
Is there a reason to cordova-plugin-firebase-analytics be a dependency?
Maven: https://mvnrepository.com/artifact/com.google.firebase/firebase-inappmessaging-display/19.0.2
Podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/0/8/b/FirebaseInAppMessagingDisplay/0.15.5/FirebaseInAppMessagingDisplay.podspec.json

**Comment by chemerisuk** [comment]
@guilhermebpereira analytics is required for Firebase inapp-messaging, it's stated in the docs.
